PYTHONTOLUA = 0
PYTHONISLEM = ""

INPUT = 0
MONEY_DIALOG = 0
ACIKARTTIRMA_ITEMLER_LIST_GELEN_TEKLIFLER = []
ACIKARTTIRMA_ITEMLER_LIST_VERILEN_TEKLIFLER = []
ACIKARTTIRMA_ITEMLER_LIST = []
ACIKARTTIRMA_ITEMLER_LIST_SIPARIS = []
ACIKARTTIRMA_PARA = 0
ACIKARTTIRMA_SATIN_AL = 0